#!/usr/bin/env python
import logging
import ROOT
import sys

logging.basicConfig()
log = logging.getLogger("merge_friends")
print(sys.argv)
output_file = sys.argv[1]

# list of friend trees with columns generated by pidgen
friends = sys.argv[2:]

logging.info("Merging pidgen output to %s", output_file)



ch = ROOT.TChain("DecayTree")
ch.Add(friends[0])

for f in friends[1:]:
    ch.AddFriend("DecayTree", f)

rdf = ROOT.RDataFrame(ch)
log.warning("Total number of candidates: ", rdf.Count().GetValue())
rdf.Snapshot("DecayTree", output_file)


# TEST
#
# pfns = [
#   "root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/MC/2012/BDD3PI.ROOT/00172448/0000/00172448_00000002_1.bdd3pi.root",
#   "root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/MC/2012/BDD3PI.ROOT/00172448/0000/00172448_00000001_1.bdd3pi.root",
#   "root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/MC/2012/BDD3PI.ROOT/00172448/0000/00172448_00000003_1.bdd3pi.root",
#   "root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/MC/2012/BDD3PI.ROOT/00172448/0000/00172448_00000004_1.bdd3pi.root",
# ]

# friends = [
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p1_fromXc_PIDK.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p1_fromXc_PIDp.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p1_fromY_PIDK.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p1_fromY_PIDp.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p2_fromXc_PIDK.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p2_fromXc_PIDp.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p2_fromY_PIDK.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p2_fromY_PIDp.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p3_fromXc_PIDK.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p3_fromXc_PIDp.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p3_fromY_PIDK.root",
#   "/eos/lhcb/user/l/lben/rds/pidgen/pidgen_2012_11266009_magup_p3_fromY_PIDp.root",
# ]
